# Example Docker Compose
services:
  frontend:
    image: ghcr.io/meyersa/cloudsct-frontend
    container_name: cloudsct-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    image: ghcr.io/meyersa/cloudsct-backend
    container_name: cloudsct-backend
    env_file:
      - .env
    restart: unless-stopped
