# Example Docker Compose
services:
  frontend:
    name: CloudSCT-Frontend
    image: ghcr.io/meyersa/cloudsct-frontend
    container_name: cloudsct-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./auth.json:/auth.json
    restart: unless-stopped
    
  backend:
    name: CloudSCT-Backend
    image: ghcr.io/meyersa/cloudsct-backend
    container_name: cloudsct-backend
    volumes:
      - ./auth.json:/auth.json
    restart: unless-stopped
